[ДЗ-11] Elasticsearch.
otusteamedu/PHP_2022 pull request #622
Opened 2023-03-30 08:38 UTC by atlance

2023-03-30 11:05 UTC, atlance commented on app/src/Bookstore/Domain/AbstractRepository.php
> +    final public function queryBuilder(): QueryBuilder
rename to `createQueryBuilder`

2023-03-30 11:06 UTC, atlance commented on app/src/Bookstore/Domain/Book/UseCase/Search/Handler.php
> +    public function __construct(private BookRepository $repository)
add `readonly` on all `__constructor`

2023-04-01 04:12 UTC, atlance commented on .env.dist
> +ES_PORT=9200
tets conversation

2023-04-01 17:35 UTC, DmitryKirillov requested changes

2023-04-01 17:35 UTC, DmitryKirillov commented on app/bin/console
> +exit($containerBuilder->get(Application::class)->run());
Этот вызов `exit()` кажется не особо нужным, у вас была какая-то причина его использовать?

2023-04-01 17:35 UTC, DmitryKirillov commented on app/bin/database
> +exit($containerBuilder->get(DatabaseFactory::class)->create());
Этот код дублирует `app/bin/console` — не сильно критично, но я бы объединил их в одном файле.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/composer.json
> +        "jolicode/elastically": "^1.8",
А почему `jolicode/elastically`? В целом я не против, но держите в голове, что он не поддерживает актуальные версии ES.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/config/es/analyzers.yaml
> +            - "russian_stop"
Вот это прямо отлично; мало кто из студентов выносит mapping-и в YAML-файлы.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/config/es/otus-shop_mapping.yaml
> +                    type: "integer"
В целом нормально, но я бы оставил для каждого из полей либо text, либо keyword (с учётом вашего видения поиска).

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Command/Book/SearchCommand.php
> +TXT,
Начиная с PHP 7.3 уже не обязательно прижимать теги Heredoc к левому краю. Правда, придётся отрезать ведущие пробелы при выводе текста.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Command/Book/SearchCommand.php
> +        ;
Если для класса `UseCase\Search\Command` важны все эти параметры, то их лучше передать в конструктор (или использовать Builder). Иначе возникает риск нарушения так называемого инварианта класса (объект вроде есть, а критически важных свойств в нём не хватает).

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Command/Book/SearchCommand.php
> +            mb_parse_str($priceRange, $filter->priceRange);
Я в целом не рекомендую использовать Си-подобные функции (которые принимают и изменяют параметры по ссылке). Это считается антипаттерном как в ООП, так и (особенно) в ФП.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Command/Book/SearchCommand.php
> +            $this->renderTable($output, $this->handler->handle($filter));
Не очень хорошо, что Команда занимается и поиском, и отображением результатов. Вы можете возразить, что Команда не должна ничего возвращать — но тогда имеет смысл задуматься, а нужна ли здесь классическая Команда.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Command/Book/SearchCommand.php
> +            $rows[] = [
В принципе, весь этот метод можно было бы написать в функциональном стиле. Встроенные PHP-шные функции для этого не очень хорошо подходят (они неконсистентны в плане порядка параметров), но есть множество отличных ФП-библиотек.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Command/Book/SearchCommand.php
> +                    array_map(fn (Shop $s) => sprintf('ул. %s (%s шт)', $s->shop, $s->stock), $book->stock)
Тут можно немного упростить, если добавить метод `__toString()` в класс `Shop`.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/AbstractRepository.php
> +class AbstractRepository
А этот класс точно должен быть обычным (не абстрактным)?

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/AbstractRepository.php
> +use JoliCode\Elastically\Client as Connection;
Похоже, что ваши доменные классы зависят от инфраструктурного слоя.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/Book/Entity/Book.php
> +    public array $stock = [];
Публичные поля у Entity позволят любому клиенту этого класса записать в них что угодно, это нарушит его инвариант.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/Book/UseCase/Search/Command.php
> +    public ?string $shopStock = null;
См. комментарий про публичные поля. По сути, теряется смысл сеттеров.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/Book/UseCase/Search/Command.php
> +    public ?array $sku = null;
Массивы лучше объявлять примерно так:

```php
public array $skus = [];
```

В большинстве случаев пустой массив красноречиво говорит о том, что данных в нём нет. NULL для этого обычно не нужен.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/Book/UseCase/Search/Command.php
> +    public function setTitle(mixed $value): self
Я не рекомендую использовать тип `mixed`. Вам здесь чётко нужна строка — об этом лучше сразу заявить в сигнатуре метода. Это позволит отловить часть проблем на этапе статанализа, другую часть — при компиляции, остаток проблем — в тестах.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/Book/UseCase/Search/Command.php
> +        }
Охранные методы в идеале должны как-то реагировать на невалидные значения. Обычная практика — выбросить исключение.

2023-04-01 17:35 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/Book/UseCase/Search/Handler.php
> +        }
**[ Продвинутая рекомендация ]** К сожалению, в PHP нет эквивалента Stream API из Java, но вы можете самостоятельно разработать несложный вспомогательный метод, чтобы получилось примерно так (код можно улучшить за счёт лябмда-функций):

```php
$query = $this
    ->createQueryBuilder()
    ->applyIfNotNull($command->title, 'addMustMatchQuery', ['title', ['query' => $command->title, 'fuzziness' => '2']])
    ->applyIfNotNull($command->category, 'addMustTerm', ['category.keyword', $command->category])
    ->applyIfNotNull($command->sku, 'addMustTerms', ['sku.keyword', $command->sku)
    // ...
    ->build();
```

Это улучшит общую читаемость. Если интересно, для PHP есть ряд неплохих библиотек (погуглите PHP monad library).

2023-04-02 07:37 UTC, atlance commented on app/src/Bookstore/Domain/Book/UseCase/Search/Handler.php
> +        }
Согласен. Куда красивее смотрится.

Но вы себе противоречите.

А именно: Когда мне из терминала прилетает в `$input->getOption(...)` всякая хрень типа `mixed` и я проверки прячу в DTO в сеттерах, то вы этим крайне недовольны.

```
        # App\Bookstore\Command\Book
        $filter = (new UseCase\Search\Command())
            ->setTitle($input->getOption('title'))
            ->setCategory($input->getOption('category'))
            // ...
        ;

        # UseCase\Search\Command
        public function setTitle(mixed $value): self
        {
            if (\is_string($value)) {
                $this->title = $value;
            }
    
            return $this;
        }
```

2023-04-02 17:47 UTC, DmitryKirillov commented on app/src/Bookstore/Domain/Book/UseCase/Search/Handler.php
> +        }
Эти две реализации действительно похожи, но только внешне:

1. Задача класса `Command` — предоставить достоверные данные для своих клиентов. Это значит, что он должен отказаться создать (или заполнить) свой объект, если ему передали хотя бы одно невалидное значение. Обычно при этом сразу выбрасывается исключение. Цепочка fluent-методов при этом **прерывается**.
2. Задача класса `Handler` — подготовить запрос для ES. Это значит, что он должен пройтись по всем свойствам объекта `Command` и обработать только те из них, значение которых не равно `NULL`. Цепочка fluent-методов при этом **не прерывается**.

Именно поэтому я рекомендовал:

- передавать все параметры `Command` в конструктор (либо использовать Builder), чтобы объект `Command` можно было создать только в валидном состоянии
- использовать fluent-методы в классе `Handler`, чтобы упростить код

Это две независимые рекомендации, которые решают абсолютно разные проблемы. Забегая вперёд, в обоих случаях оптимальнее всего использовать паттерн Builder — но мы до него доберёмся только к концу апреля.

2023-04-03 18:10 UTC, atlance commented on app/bin/database
> +exit($containerBuilder->get(DatabaseFactory::class)->create());
Этот код вызывается 1 раз при инициализации.
Не хотелось бы вызывать постоянные проверки существования индексов в еластике.

2023-04-03 18:13 UTC, atlance commented on app/src/Bookstore/Domain/Book/UseCase/Search/Command.php
> +    public ?array $sku = null;
на `null` осуществлять проверки проще, особенно если у нас идёт работа с универсальными методами вроде `applyIfNotNull`

2023-09-06 05:55 UTC, closed without merging